"""molwatch parser registry.

Adding support for a new output format is two steps:
  1. drop a new ``foo.py`` module here that defines a ``FooParser``
     subclass of ``TrajectoryParser`` (see base.py for the contract);
  2. import it below and append the class to ``PARSERS``.

The Flask app calls :func:`detect_parser` on every load and never
references a specific parser by name.
"""

from __future__ import annotations

import os
from typing import List, Type

from .base import TrajectoryParser
from .molwatch_log import MolwatchLogParser
from .siesta import SiestaParser
from .pyscf import PySCFParser


# Order matters: the first parser whose ``can_parse(path)`` returns
# True wins.  Put more-specific parsers (with stricter format markers)
# first so they aren't shadowed by a permissive one.
#
# MolwatchLogParser goes first: its header marker
# ``# molwatch trajectory log`` is unambiguous and won't false-match
# any engine-native format.  This is the preferred path for any run
# generated by molbuilder -- a single self-contained file with the
# whole trajectory + per-cycle SCF data, no sibling-file discovery
# needed.  SIESTA and raw PySCF parsers remain as fallbacks for runs
# that weren't generated through molbuilder.
PARSERS: List[Type[TrajectoryParser]] = [
    MolwatchLogParser,
    SiestaParser,
    PySCFParser,
]


class UnknownFormatError(ValueError):
    """No registered parser claims to understand this file."""


def detect_parser(path: str) -> Type[TrajectoryParser]:
    """Return the first parser class whose ``can_parse(path)`` is True.

    Raises :class:`UnknownFormatError` if no parser matches; the error
    message lists every registered format with its hint, plus a
    targeted suggestion for the most common foot-gun (uploading the
    PySCF .log instead of the geomeTRIC _optim.xyz).
    """
    for cls in PARSERS:
        try:
            if cls.can_parse(path):
                return cls
        except Exception:
            # A parser's sniffer should never raise -- but if it does,
            # don't let one buggy parser take down the dispatch.
            continue

    base = os.path.basename(path)
    lines = [f"No registered parser knows how to handle {base!r}."]
    lines.append("Supported formats:")
    for c in PARSERS:
        suffix = f" -- {c.hint}" if c.hint else ""
        lines.append(f"  * {c.label}{suffix}")

    # Filename-based hints for the two most common mistakes.  These
    # are pure heuristics: we only trigger them on filename patterns
    # that are unambiguous about user intent, so a real misfire is
    # cheap.
    lower = base.lower()

    # 1. .fdf is the SIESTA INPUT, not its output.  SIESTA writes
    #    output to wherever stdout was redirected (typically
    #    siesta.out / <label>.out).  Easy mistake because the .fdf
    #    is the file molbuilder hands the user.
    if lower.endswith(".fdf"):
        stem = base[:-len(".fdf")]
        lines.append("")
        lines.append(
            f"That looks like a SIESTA INPUT file (.fdf), not the "
            f"output.  SIESTA writes its output to wherever you "
            f"redirected stdout, typically:"
        )
        lines.append(f"    mpirun siesta < {base} > {stem}.out")
        lines.append(
            f"Load '{stem}.out' (or whatever you redirected to) "
            f"instead.  If you generated this run with molbuilder, "
            f"there's also a '{stem}.molwatch.log' alongside it that "
            f"shows the initial geometry immediately."
        )

    # 2. PySCF .log is the runtime log; the parser wants the
    #    geomeTRIC trajectory <job>_geom_optim.xyz instead.  Stem-
    #    match so we don't spam the suggestion for SIESTA users
    #    (whose main output ALSO often ends in .log).
    elif (lower.endswith(".log") and
          ("pyscf" in lower or "_relax" in lower or "geom" in lower)):
        stem = base
        for suffix in (".log", "_geom.log", "_pyscf.log"):
            if stem.endswith(suffix):
                stem = stem[: -len(suffix)]
                break
        lines.append("")
        lines.append(
            f"Looks like a PySCF run -- load the geomeTRIC trajectory "
            f"'{stem}_geom_optim.xyz' instead.  If you generated this "
            f"run with molbuilder, '{stem}.molwatch.log' is the "
            f"preferred single-file input."
        )

    # 3. Generic catch-all hint pointing at the debug guide.  Always
    #    safe to include and steers the user to the docs that explain
    #    what each parser actually checks.
    else:
        lines.append("")
        lines.append(
            "See README.md ('How auto-detection decides') or "
            "docs/spec/parsers.md ('Detection order and debugging') "
            "for the per-parser detection rules and a debug checklist."
        )

    raise UnknownFormatError("\n".join(lines))


def parser_summary() -> List[dict]:
    """Lightweight metadata used by the /api/formats endpoint."""
    return [
        {"name": c.name, "label": c.label, "hint": c.hint}
        for c in PARSERS
    ]


__all__ = [
    "PARSERS",
    "TrajectoryParser",
    "UnknownFormatError",
    "detect_parser",
    "parser_summary",
]
